import assert from "./assert";
import testInfoAntC from './antC';
import testInfoAntH from './antH';
import testInfoCommandC from './command_line_argsC';
import testInfoEmptyC from './empty';
import testInfoHandleAddC from './handle_addC';
import testInfoHandleChangeC from './handle_changeC';
import testInfoHeaderGH from './header_w_guardsH';
import testInfoMainC from './mainC';
import testInfoMovieC from './movieC';
import testInfoMovieH from './movieH';
import testInfoMovieOPC from './movie_operationsC';
import testInfoParserC from './parserC';
import testInfoSimulationC from './simulationC';
import testInfoStrC from './strC';
import testInfoStrH from './strH';
import testInfoGridC from "./gridC";


assert(testInfoAntC);
assert(testInfoAntH);
assert(testInfoCommandC);
assert(testInfoEmptyC);
assert(testInfoGridC);
assert(testInfoHandleAddC);
assert(testInfoHandleChangeC);
assert(testInfoHeaderGH);
assert(testInfoMainC);
assert(testInfoMovieC);
assert(testInfoMovieH);
assert(testInfoMovieOPC);
assert(testInfoParserC);
assert(testInfoSimulationC);
assert(testInfoStrC);
assert(testInfoStrH);
