enum TokenType {
  // Special
  specialComma,
  specialSemicolon,
  specialBracketLeft,
  specialBracketRight,
  specialParenLeft,
  specialParenRight,
  specialBraceLeft,
  specialBraceRight,

  // Preprocessor (https://www.cprogramming.com/reference/preprocessor/)
  // preproDirectiveNull,
  preproOperatorConcat,
  preproDirectiveInclude,
  preproStandardHeader,
  preproDirectiveDefine,
  preproDirectiveContinuation,
  preproDirectiveUndef,
  preproDirectiveIf,
  preproDirectiveIfdef,
  preproDirectiveIfndef,
  preproMacroError,
  preproMacroFile,
  preproMacroLine,
  preproMacroDate,
  preproMacroTime,
  preproMacroTimestamp,
  preproDirectivePragma,

  // Unary operators
  operatorUnaryIncrement,
  operatorUnaryDecrement,
  operatorUnaryOnesComplement,
  operatorUnaryLogicalNegation,
  operatorUnaryIndirection,
  operatorUnaryDereference,
  // Binary operators
  operatorBinaryAdd,
  operatorBinarySubtract,
  operatorBinaryDivide,
  operatorBinaryMultiply,
  operatorBinaryModulus,
  operatorBinaryEqual,
  operatorBinaryNotEqual,
  operatorBinaryGreater,
  operatorBinaryGreaterEqual,
  operatorBinaryLess,
  operatorBinaryLessEqual,
  operatorBinaryLogicalAnd,
  operatorBinaryLogicalOr,
  operatorBinaryBitwiseAnd,
  operatorBinaryBitwiseOr,
  operatorBinaryBitwiseXor,
  operatorBinaryBitwiseShiftLeft,
  operatorBinaryBitwiseShiftRight,
  operatorBinaryAssignment,
  operatorBinaryAddAssignment,
  operatorBinarySubtractAssignment,
  operatorBinaryMultiplyAssignment,
  operatorBinaryDivideAssignment,
  operatorBinaryModulusAssignment,
  operatorBinaryBitwiseShiftLeftAssignment,
  operatorBinaryBitwiseShiftRightAssignment,
  operatorBinaryBitwiseAndAssignment,
  operatorBinaryBitwiseOrAssignment,
  operatorBinaryBitwiseXorAssignment,
  operatorBinaryMemberAccess,
  operatorBinaryArrow,
  // Miscellanous operators
  operatorMiscTernaryQuestion,
  operatorMiscTernaryColon,

  // Constants
  constantNumber,
  constantCharacter,
  constantString,

  // Keywords (https://en.cppreference.com/w/c/keyword)
  keywordAlignas,
  keywordAlignof,
  keywordAuto,
  keywordAtomic,
  keywordBool,
  keywordBreak,
  keywordCase,
  keywordChar,
  keywordComplex,
  keywordConst,
  keywordContinue,
  keywordDefault,
  keywordDo,
  keywordDouble,
  keywordElse,
  keywordEnum,
  keywordExtern,
  keywordFloat,
  keywordFor,
  keywordGeneric,
  keywordGoto,
  keywordIf,
  keywordImaginary,
  keywordInt,
  keywordLong,
  keywordNoreturn,
  keywordRegister,
  keywordReturn,
  keywordShort,
  keywordSigned,
  keywordSizeof,
  keywordStatic,
  keywordStaticassert,
  keywordStruct,
  keywordSwitch,
  keywordThreadlocal,
  keywordTypedef,
  keywordUnion,
  keywordUnsigned,
  keywordVoid,
  keywordVolatile,
  keywordWhile,

  // Other
  identifier,
  label,
}

export default TokenType;
